swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article

basePath: "/api"
# paths supported by serve application
paths:
  /article:
    get:
      operationId: "article.read"
      tags:
        - "Article"
      summary: "The article data structure supported by the server applications"
      description: "Read the list of articles"
      responses:
        200:
          description: "Successful read article list operation"
          schema:
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                body:
                  type: "string"
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"